version: '3'
services:
  login:
    build:
      context: ../LoginService
      dockerfile: Dockerfile
    image: elcostalitoalegre/sparkweblive:loginservice
    container_name: LoadBalancerAPP
    ports:
      - "5000:6000"
  other:
    build:
      context: ../OtherService
      dockerfile: Dockerfile
    image: elcostalitoalegre/sparkweblive:otherservice   
    ports:
      - "5001:6000"
  
